version: '3.4'

services:
  dailyplanner_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5432:5432"
    networks:
      - shared_daily_planner
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  dailyplanner_api:
    ports:
      - "10000:80"
    networks:
      - shared_daily_planner
    env_file:
      - env.api

  dailyplanner_rabbitmq:
    ports:
     - "5672:5672"
     - "5673:5673"
     - "15672:15672"
    networks:
     - shared_daily_planner
    volumes:
     - ./rabbitmq:/var/lib/rabbitmq

  dailyplanner_identity:
    ports:
      - "10001:80"
    networks:
      - shared_daily_planner
    env_file:
      - env.identity

  dailyplanner_worker:
    networks:
      - shared_daily_planner
    env_file:
      - env.worker

networks:
  shared_daily_planner:
    name: daily_planner
    driver: bridge