version: '3.4'

services:
  dailyplanner_postgresql:
    image: postgres:14.1

  dailyplanner_api:
    image: ${DOCKER_REGISTRY-}dailyplannerapi
    build:
      context: .
      dockerfile: Systems/Api/DailyPlanner.Api/Dockerfile
    depends_on:
      - dailyplanner_postgresql

  dailyplanner_rabbitmq:
    image: rabbitmq:management
  
  dailyplanner_identity:
    image: ${DOCKER_REGISTRY-}dailyplanneridentity
    build:
      context: .
      dockerfile: Systems/Identity/DailyPlanner.Identity/Dockerfile
    depends_on:
      - dailyplanner_api
      - dailyplanner_postgresql
  
  dailyplanner_worker:
    image: ${DOCKER_REGISTRY-}dailyplannerworker
    build:
      context: .
      dockerfile: Systems/Workers/DailyPlanner.Worker/Dockerfile
    depends_on:
      - dailyplanner_api
      - dailyplanner_postgresql
      - dailyplanner_rabbitmq