version: '3.4'

services:
  dailyplanner_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5432:5432"
    networks:
      - shared_daily_planner
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data


  dailyplanner_api:
    ports:
      - "10000:80"
    networks:
      - shared_daily_planner
    env_file:
      - env.api

networks:
  shared_daily_planner:
    name: daily_planner
    driver: bridge