version: '3.4'

services:
  dailyplanner_api:
    ports:
      - "10000:80"
    networks:
      - shared_daily_planner
    env_file:
      - env.api

networks:
  shared_daily_planner:
    name: daily_planner
    driver: bridge